name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv (fast pip replacement)
        run: |
          pip install uv

      - name: Install project with dev dependencies
        run: |
          uv pip install -e .[dev]

      - name: Run pre-commit (lint + type-check)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run test suite
        run: |
          pytest -q
